### ISSUE TITLE
US14 - Eu, como desenvolvedor, desejo fazer o CRUD de usuários para que eu possa armazenar os dados do mesmo.

### ISSUE THREAD

**Issue by sudjoao** [OrcestraGamificacao/DesafioCovid19-Back#1]
## Descrição da Issue
Fazer o CRUD(Create, Read, Update and Delete) de usuário.
### Tasks: 
- [x] Criar o usuário no banco com as informações necessárias;
- [x] Criar os métodos do CRUD.

### Critérios de aceitação
- [ ] O usuário ter todas as informações necessárias para o funcionamento do aplicativo;
- [x]  Ser capaz de cadastrar um usuário;
- [x] Ser capaz de ver um usuário;
- [x] Ser capaz de editar dados de um usuário;
- [x] Ser capaz de excluir um usuário.

**Comment by CalebeRios** [comment]
Quais são os dados necessários para o usuário poder criar uma conta?

**Comment by devsalula** [comment]
@CalebeRios acredito que nome, email, cpf, senha sejam o suficientes, não?
