### ISSUE TITLE
US15 - Eu, como desenvolvedor, desejo guardar quais são lugares de aglomeração para mostrar para pessoas

### ISSUE THREAD

**Issue by sudjoao** [OrcestraGamificacao/DesafioCovid19-Back#2]
## Descrição da Issue
Pegar informações sobre a localização de lugares de aglomeração que foram reportados pelos usuários e guardar essa informação para mostrar ao usuário no mapa.

### Tasks: 
- [ ] Descobrir quais são as informações de localização que a pessoa passa quando reporta um lugar;
- [ ] Guardar essas informações.

### Critérios de aceitação
- [ ] Ser capaz de mostrar essas informações no mapa.
