### ISSUE TITLE
US17 - Eu, como desenvolvedor, desejo descobrir como trabalhar com localização/mapas para conseguir mostrar os lugares com aglomeração

### ISSUE THREAD

**Issue by sudjoao** [OrcestraGamificacao/DesafioCovid19-Back#3]
## Descrição da Issue
Descobrir uma maneira de mexer com mapa em NodeJS e aplica-la no back para que seja possível mostrar as informações desejadas no front.
### Tasks: 
- [ ] Descobrir como trabalhar com mapas/localização;
- [ ] Implementar no código.

### Critérios de aceitação
- [ ] Ser possível fazer o foco do aplicativo que é mostrar um mapa e ser possível enviar informações sobre os locais que tem aglomeração e mostrar as mesmas no mapa.
