### ISSUE TITLE
US18 - Eu, como Desenvolvedor, desejo salvar os pontos do ranking para o desafio das comunidades.

### ISSUE THREAD

**Issue by devsalula** [OrcestraGamificacao/DesafioCovid19-Back#5]
## Descrição da Issue
Pegar as informações de pontos do desafio das comunidades de cada usuário e salvá-los no banco de dados.

### Tasks: 
- [ ] Receber a quantidade de pontos do front
- [ ] Salvar no mongo

### Critérios de aceitação
- [ ] Pontos devem ser salvos no perfil de cada usuário
- [ ] Deve haver uma model
